### ISSUE TITLE
网络一直失败问题

### ISSUE THREAD

**Issue by BenchuYee** [lihen233/iwara#1]
换了多个网络似乎下载时都会网络错误然后超出重试次数，网络都挂了梯子。

**Comment by lihen233** [comment]
1、iwara本身用着就不稳定
2、此脚本是复制自 https://github.com/WriteCode-ChangeWorld/Tools。我本身只用iwara部分，做的修改也只更改了下载路径以匹配我自己的使用环境

**Comment by lihen233** [comment]
> 换了多个网络似乎下载时都会网络错误然后超出重试次数，网络都挂了梯子。

1、iwara本身用着就不稳定
2、此脚本是复制自 https://github.com/WriteCode-ChangeWorld/Tools     我本身只用iwara部分，做的修改也只更改了下载路径以匹配我自己的使用环境
